#spring.jpa.hibernate.ddl-auto: create-drop
spring.thymeleaf.cache: false
banner:
  location: banner.txt
server.port : 80
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:d:/tmp/customer # H2데이터베이스 기능 중 파일 데이터베이스를 사용하여 데이터가 지워지지않고 지속되도록 함
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate
  thymeleaf.cache: false
